# Generated by Django 4.2.1 on 2023-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
