# Generated by Django 4.2.1 on 2023-05-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_new_content_alter_new_image_alter_new_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
