# Generated by Django 4.2.1 on 2023-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
